---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'api/v/1/signout' : 'App\Web\API\SignoutAPI'
    'api/v/1/search' : 'App\Web\API\SearchAPI'
    'api/v/1/contact' : 'App\Web\API\ContactAPI'
    'api/v/1/session/$action' : 'App\Web\API\SessionAPI'
    'api/v/1/subscribe' : 'App\Web\API\SubscriptionAPI'
    'token-login': 'App\Web\Layout\RecoveryController'
    'api/v/1/company' : 'App\Web\API\CompanyAPI'
    # new api
    'api/v/1/authorise': 'App\Web\API\Authorise'
    'api/v/1/member/$action': 'App\Web\API\Member'
    'api/v/1/sd-application/$action': 'App\Web\API\StudentDiscountApplication'
    'api/v/1/job-referral/$action/$ID': 'App\Web\JobReferral\API\ReferralOpportunityAPI'
    'member/$action/$id': 'App\Web\Page\MemberCentreController'
    'referral-opportunities/$action/$id': 'App\Web\Layout\ReferralOpportunityController'
