export default {
  isLoading: false,
  isMobile: false,
  error: null,
  site_data: window.appInitialData,
  showSigninForm: false,
  showModal: false,
  postbackMessage: null,
  modalColor: 'primary',
  access_token: null,
  user: null,
  stripeKey: null,
  refreshingToken: true,
  skipFetchOnce: false,
  width: 320,
  memberMenuShown: false,
}
