export { default as HomePage } from './types/HomePage'
export { default as TeamPage } from './types/TeamPage'
export { default as CertificatesPage } from './types/CertificatesPage'
export { default as SignupPage } from './types/SignupPage'
export { default as MemberCentre } from './types/MemberCentre'
export { default as Page } from './types/Page'
